import { ServiceNowFeatureContext } from './service-now.config';
import { ServiceNowFeature } from './service-now.constants';

export const featureContexts: ServiceNowFeatureContext[] = [
  {
    feature: ServiceNowFeature.SUAADHYA_CERTIFICATE,
    static: {},
    params: {
      id: 'id',
      sys_id: 'sys_id',
      language: 'language',
      reportingCountry: 'reportingCountry',
      projectNumber: 'projectNumber',
      certificateNumber: 'certificateNumber',
      revisionNumber: 'revisionNumber',
      certificateID: 'certificateID',
      certificateStatus: 'certificateStatus',
      service: 'service',
      accountSuaadhyaId: 'accountSuaadhyaId',
    },
  },
  {
    feature: ServiceNowFeature.SUAADHYA_INVOICE,
    static: {},
    params: {
      id: 'id',
      sys_id: 'sys_id',
      language: 'language',
      reportingCountry: 'reportingCountry',
      projectNumber: 'projectNumber',
      invoice: 'invoice',
      status: 'status',
      accountSuaadhyaId: 'accountSuaadhyaId',
    },
  },
  {
    feature: ServiceNowFeature.SUAADHYA_SCHEDULE,
    static: {},
    params: {
      id: 'id',
      sys_id: 'sys_id',
      language: 'language',
      reportingCountry: 'reportingCountry',
      projectNumber: 'projectNumber',
      startDate: 'startDate',
      endDate: 'endDate',
      auditID: 'auditID',
      siteAuditID: 'siteAuditID',
      siteAddress: 'siteAddress',
      site: 'site',
      status: 'status',
      service: 'service',
      siteCity: 'siteCity',
      siteZip: 'siteZip',
      siteCountry: 'siteCountry',
      siteState: 'siteState',
      accountSuaadhyaId: 'accountSuaadhyaId',
    },
  },
  {
    feature: ServiceNowFeature.SUAADHYA_COMPANY,
    static: {},
    params: {
      id: 'id',
      sys_id: 'sys_id',
      language: 'language',
      reportingCountry: 'reportingCountry',
      accountSuaadhyaId: 'accountSuaadhyaId',
      account_id: 'account_id',
      accountName: 'organizationName',
      accountAddress: 'accountAddress',
    },
  },
  {
    feature: ServiceNowFeature.HOME,
    static: {},
    params: {
      language: 'language',
      reportingCountry: 'reportingCountry',
    },
  },
  {
    feature: ServiceNowFeature.CATALOG_ITEM,
    static: {},
    params: {
      id: 'id',
      sys_id: 'sys_id',
      language: 'language',
      table: 'table',
    },
  },
];
