import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const CONTRACTS_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'contractName',
    displayName: 'contracts.contractsList.contractName',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: true,
    sticky: false,
    width: '30rem',
  },
  {
    field: 'contractType',
    displayName: 'contracts.contractsList.contractType',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
    width: '12rem',
  },
  {
    field: 'company',
    displayName: 'contracts.contractsList.company',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'service',
    displayName: 'contracts.contractsList.services',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: true,
    fixed: false,
    sticky: false,
  },
  {
    field: 'sites',
    displayName: 'contracts.contractsList.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: true,
    fixed: false,
    sticky: false,
  },
  {
    field: 'dateAdded',
    displayName: 'contracts.contractsList.dateAdded',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
    width: '12rem',
  },
  {
    field: 'actions',
    displayName: '',
    type: ColumnType.Actions,
    cellType: CellType.Actions,
    hidden: false,
    fixed: true,
    hideFromColumnManagement: true,
    sticky: true,
  },
];
