import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const SCHEDULES_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'startDate',
    displayName: 'schedules.scheduleList.startDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'endDate',
    displayName: 'schedules.scheduleList.endDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'status',
    displayName: 'schedules.scheduleList.status',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Status,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'service',
    displayName: 'schedules.scheduleList.service',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'site',
    displayName: 'schedules.scheduleList.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'city',
    displayName: 'schedules.scheduleList.city',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'auditType',
    displayName: 'schedules.scheduleList.auditType',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'leadAuditor',
    displayName: 'schedules.scheduleList.leadAuditor',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'siteRepresentative',
    displayName: 'schedules.scheduleList.siteRepresentative',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'company',
    displayName: 'schedules.scheduleList.company',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'siteAuditId',
    displayName: 'schedules.scheduleList.siteAuditId',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: true,
    fixed: false,
    sticky: false,
  },
  {
    field: 'eventActions',
    displayName: '',
    type: ColumnType.EventActions,
    cellType: CellType.EventActions,
    hidden: false,
    fixed: true,
    sticky: true,
    hideFromColumnManagement: true,
  },
];
