import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const SUB_AUDIT_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'startDate',
    displayName: 'audit.auditDetails.subAudits.startDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'endDate',
    displayName: 'audit.auditDetails.subAudits.endDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'status',
    displayName: 'audit.auditDetails.subAudits.status',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Status,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'service',
    displayName: 'audit.auditDetails.subAudits.service',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'site',
    displayName: 'audit.auditDetails.subAudits.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'city',
    displayName: 'audit.auditDetails.subAudits.city',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'auditorTeam',
    displayName: 'audit.auditDetails.subAudits.auditorTeam',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
];
