import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const AUDIT_FINDING_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'findingNumber',
    displayName: 'audit.auditDetails.findings.findingNumber',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Link,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'status',
    displayName: 'audit.auditDetails.findings.status',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Status,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'companyName',
    displayName: 'audit.auditDetails.findings.company',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'title',
    displayName: 'audit.auditDetails.findings.title',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'category',
    displayName: 'audit.auditDetails.findings.category',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Tag,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'services',
    displayName: 'audit.auditDetails.findings.services',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'site',
    displayName: 'audit.auditDetails.findings.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'city',
    displayName: 'audit.auditDetails.findings.city',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'auditNumber',
    displayName: 'audit.auditDetails.findings.auditNumber',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'openDate',
    displayName: 'audit.auditDetails.findings.openDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'closeDate',
    displayName: 'audit.auditDetails.findings.closeDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: true,
    fixed: false,
    sticky: false,
  },
  {
    field: 'acceptedDate',
    displayName: 'audit.auditDetails.findings.acceptedDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: true,
    fixed: false,
    sticky: false,
  },
];
