import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const MEMBERS_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'name',
    displayName: 'settings.membersTab.name',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.TextWithIcon,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'email',
    displayName: 'settings.membersTab.email',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'company',
    displayName: 'settings.membersTab.company',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'services',
    displayName: 'settings.membersTab.service',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'sites',
    displayName: 'settings.membersTab.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'access',
    displayName: 'settings.membersTab.access',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'eventActions',
    displayName: '',
    type: ColumnType.EventActions,
    cellType: CellType.EventActions,
    hidden: false,
    fixed: true,
    sticky: true,
    customClass: 'table-header-dimension-event-actions--sm',
    hideFromColumnManagement: true,
  },
];
