export const DownloadType = {
  ContractBulk: 'contract-bulk',
  Contract: 'contract',
  ContractExcel: 'contract-excel',
  AuditExcel: 'audit-excel',
  FindingExcel: 'finding-excel',
  Invoice: 'invoice',
  InvoiceBulk: 'invoice-bulk',
  InvoiceExcel: 'invoice-excel',
  ScheduleExcel: 'schedule-excel',
  CertificateExcel: 'certificate-excel',
  FindingDetails: 'finding-details',
  FindingDetailBulk: 'finding-detail-bulk',
  AuditDetails: 'audit-details',
  AuditDetailBulk: 'audit-detail-bulk',
  AuditFindingExcel: 'audit-finding-excel',
  SubAuditExcel: 'sub-audit-excel',
  CertificationMark: 'certification-mark',
  Certificate: 'certificate',
  CertificateBulk: 'certificate-bulk',
} as const;

export const DownloadTypeName = {
  ContractBulk: 'Download Contracts',
  Contract: 'Download Contract',
  ContractExcel: 'Download Contracts Excel',
  AuditExcel: 'Download Audits Excel',
  FindingExcel: 'Download Findings Excel',
  InvoiceBulk: 'Download Invoices',
  InvoiceExcel: 'Download Invoices Excel',
  Invoice: 'Download Invoice',
  Audit: 'Download Audit',
  Finding: 'Download Finding',
  ScheduleExcel: 'Download Schedules Excel',
  CertificateExcel: 'Download Certificates Excel',
  FindingDetails: 'Download Finding Details',
  FindingDetailBulk: 'Download Finding Details',
  AuditDetails: 'Download Audit Detail',
  AuditDetailBulk: 'Download Audit Details',
  AuditFindingExcel: 'Download Audit Findings Excel',
  SubAuditExcel: 'Download Sub Audits Excel',
  CertificationMark: 'Download Certification Mark',
  Certificate: 'Download Certificate',
  CertificateBulk: 'Download Certificate Bulk',
} as const;

export const DownloadFileNames = {
  FindingExcel: 'finding.xlsx',
  AuditExcel: 'audit.xlsx',
  ContractExcel: 'contracts.xlsx',
  InvoiceExcel: 'financial.xlsx',
  ScheduleExcel: 'schedule.xlsx',
  CertificateExcel: 'certificates.xlsx',
  AuditFindingsExcel: 'auditFindings.xlsx',
  SubAuditExcel: 'subaudit.xlsx',
} as const;
