import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const ACTIONS_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'actionName',
    displayName: 'actions.gridHeading.actionName',
    type: ColumnType.Text,
    cellType: CellType.TextWithIcon,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'dueDate',
    displayName: 'actions.gridHeading.dueOn',
    type: ColumnType.Text,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'message',
    displayName: 'actions.gridHeading.message',
    type: ColumnType.Text,
    cellType: CellType.HtmlText,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'service',
    displayName: 'actions.gridHeading.service',
    type: ColumnType.Text,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'site',
    displayName: 'actions.gridHeading.site',
    type: ColumnType.Text,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'actions',
    displayName: '',
    type: ColumnType.Actions,
    cellType: CellType.Actions,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'entityType',
    displayName: 'entityType',
    type: ColumnType.Text,
    cellType: CellType.Text,
    hidden: true,
    fixed: false,
    sticky: false,
  },
];
