import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const FINDINGS_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'findingNumber',
    displayName: 'findings.findingsList.findingsNumber',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Link,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'response',
    displayName: 'findings.findingsList.response',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'status',
    displayName: 'findings.findingsList.status',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Status,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'title',
    displayName: 'findings.findingsList.title',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'category',
    displayName: 'findings.findingsList.category',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Tag,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'companyName',
    displayName: 'findings.findingsList.company',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'services',
    displayName: 'findings.findingsList.service',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'site',
    displayName: 'findings.findingsList.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'country',
    displayName: 'findings.findingsList.country',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'city',
    displayName: 'findings.findingsList.city',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'openDate',
    displayName: 'findings.findingsList.openDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'closeDate',
    displayName: 'findings.findingsList.closeDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: true,
    fixed: false,
    sticky: false,
  },
  {
    field: 'acceptedDate',
    displayName: 'findings.findingsList.acceptedDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: true,
    fixed: false,
    sticky: false,
  },
  {
    field: 'findingsId',
    displayName: 'findings.findingsList.id',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: true,
    fixed: false,
    sticky: false,
  },
];
