import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared/models';

export const INVOICE_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'invoiceId',
    displayName: 'invoices.invoicesList.invoiceNumber',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Link,
    hidden: false,
    fixed: true,
    sticky: false,
  },
  {
    field: 'status',
    displayName: 'invoices.invoicesList.status',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Status,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'amount',
    displayName: 'invoices.invoicesList.amount',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
    customClass: 'change-color',
  },
  {
    field: 'billingAddress',
    displayName: 'invoices.invoicesList.billingAddress',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'dueDate',
    displayName: 'invoices.invoicesList.dueDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'referenceNumber',
    displayName: 'invoices.invoicesList.referenceNumber',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'issueDate',
    displayName: 'invoices.invoicesList.issueDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'contactPerson',
    displayName: 'invoices.invoicesList.contact',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'company',
    displayName: 'invoices.invoicesList.company',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'plannedPaymentDate',
    displayName: 'invoices.invoicesList.paymentDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'originalInvoiceNumber',
    displayName: 'invoices.invoicesList.originalInvoice',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'actions',
    displayName: '',
    type: ColumnType.Actions,
    cellType: CellType.Actions,
    hidden: false,
    fixed: true,
    sticky: true,
    hideFromColumnManagement: true,
  },
  {
    field: 'eventActions',
    displayName: '',
    type: ColumnType.EventActions,
    cellType: CellType.EventActions,
    hidden: false,
    fixed: true,
    sticky: true,
    customClass: 'table-header-dimension-event-actions--sm',
    hideFromColumnManagement: true,
  },
];
