import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const CERTIFICATE_DOCUMENTS_COLUMNS: ColumnDefinition[] = [
  {
    field: 'fileName',
    displayName: 'certificate.attachedDocuments.fileName',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'type',
    displayName: 'certificate.attachedDocuments.type',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'dateAdded',
    displayName: 'certificate.attachedDocuments.dateAdded',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'uploadedBy',
    displayName: 'certificate.attachedDocuments.uploadedBy',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'language',
    displayName: 'certificate.attachedDocuments.language',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'actions',
    displayName: '',
    type: ColumnType.Actions,
    cellType: CellType.Actions,
    hidden: false,
    fixed: false,
    sticky: true,
    hideFromColumnManagement: true,
  },
];
