import {
  CellType,
  ColumnDefinition,
  ColumnType,
} from '@customer-portal/shared';

export const CERTIFICATE_LIST_COLUMNS: ColumnDefinition[] = [
  {
    field: 'certificateNumber',
    displayName: 'certificate.certificateList.certificateNumber',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Link,
    hidden: false,
    fixed: true,
    sticky: false,
    routeIdField: 'certificateId',
  },
  {
    field: 'companyName',
    displayName: 'certificate.certificateList.company',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'service',
    displayName: 'certificate.certificateList.service',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'status',
    displayName: 'certificate.certificateList.status',
    type: ColumnType.CheckboxFilter,
    cellType: CellType.Status,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'validUntil',
    displayName: 'certificate.certificateList.validUntil',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'issuedDate',
    displayName: 'certificate.certificateList.issuedDate',
    type: ColumnType.DateFilter,
    cellType: CellType.Date,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'site',
    displayName: 'certificate.certificateList.site',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'city',
    displayName: 'certificate.certificateList.city',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: false,
    fixed: false,
    sticky: false,
  },
  {
    field: 'certificateId',
    displayName: 'certificate.certificateList.certificateId',
    type: ColumnType.SearchCheckboxFilter,
    cellType: CellType.Text,
    hidden: true,
    fixed: false,
    sticky: false,
  },
];
